{% set name = "cascade" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9081ff90c297504e1dd3fa35a8965961f1da987241160e593c31e7c8168ea13c

build:
  number: 0
  ignore_run_exports:
    # NOTE: hdf5 is used only in the tests.
    - hdf5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - tbb-devel
    - libboost-devel
    - fmt
    - heyoka =3.*
    - spdlog
    - xtensor
    - xtensor-blas
    - hdf5

  run:
    - python
    - numpy
    - heyoka.py =3.*

about:
  home: https://esa.github.io/cascade/
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: N-body simulation for the evolution of orbital environments

extra:
  recipe-maintainers:
    - darioizzo
    - bluescarni
