{% set name = "cascade" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 50a6f06fc01db83a1f160f86f15f7316205eba523309c7eb31007d549f37e5f9

build:
  number: 0
  ignore_run_exports:
    # NOTE: hdf5 is used only in the tests.
    - hdf5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.10                        # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - tbb-devel
    - libboost-devel
    - fmt
    - heyoka >=7.4 # required as per xtensor 0.26 compatibility
    - spdlog
    - xtensor
    - xtensor-blas >=0.26 # required as per heyoka >= 7.4 compatibility
    - hdf5

  run:
    - python
    - numpy
    - heyoka.py >=7.4

about:
  home: https://esa.github.io/cascade/
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: N-body simulation for the evolution of orbital environments

extra:
  recipe-maintainers:
    - darioizzo
    - bluescarni
