{% set name = "cascade" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f21352d53f90bbf94d1b2c841108e5efd05d37a141896efcabce04ca728b2dc0

build:
  number: 0
  ignore_run_exports:
    # NOTE: hdf5 is used only in the tests.
    - hdf5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - tbb-devel
    - libboost-devel
    - fmt
    - heyoka >=0.21.0
    - spdlog
    - xtensor
    - xtensor-blas
    - hdf5

  run:
    - python
    - numpy
    - heyoka.py >=0.21.0

test:
  commands:
    - python -c "from cascade import test; test.run_test_suite()"

about:
  home: https://esa.github.io/cascade/
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: N-body simulation for the evolution of orbital environments

extra:
  recipe-maintainers:
    - darioizzo
    - bluescarni
